mono/monkeywrench

MonkeyWrench.Web.UI/Code/Utils.cs
MonkeyWrench.Web.UI/MonkeyWrench.Web.UI.csproj
MonkeyWrench.Web.UI/index.aspx.cs
MonkeyWrench.Web.WebService/WebServices.asmx.cs

The current flow of the index page is to call the function `WebServices.GetFrontPageDataWithTags`, which makes a SOAP request to the WebServices server (which, for private wrench, is the same as the Web UI server), which in turn queries the database and returns a response. After profiling, we have determined that making the SOAP request and [de]serializing the data to XML adds a ~200% overhead to the call to `WebServices.GetFrontPageDataWithTags`.
This patch changes the index page so that it creates a local version of the `WebServices` object, and uses that to directly return the results of `WebServices.GetFrontPageDataWithTags`, bypassing the SOAP interface entirely.
This requires that the Web UI server is configured with the database credentials (which is already the case if the same …

Speed up the front page by bypassing SOAP in using WebServices

---

MonkeyWrench.DataClasses/Database/DBRecord.cs
MonkeyWrench.Web.UI/Code/Utils.cs
MonkeyWrench.Web.UI/Master.master.cs
MonkeyWrench.Web.WebService/WebServices.asmx.cs

This branch amortizes the cost of reflection and fetching ordinals over an entire query when reading to ORM objects. 
The current method of reading rows into ORM objects is similar to this:
var myModels = new List<MyModel>();
while (reader.Read())
myModels.Add(new MyModel(reader))
The constructor for `DBRecord` uses reflection to map columns to class attributes. However, the constructor re-fetches the reflection information each time it is called, which is an expensive operation. Additionally, [the MSDN docs for `GetOrdinal`] (which the constructor also fetches every time it is ran) mention that it is somewhat costly as well.
This patch adds a static method: `DBRecord.LoadMany<T>(IDataReader)`, which caches the field-ordinal mappings across a query and reflection information when first …

Cache reflection information for models.

---

MonkeyWrench.Web.UI/Admin.aspx.cs
MonkeyWrench.Web.UI/BuildBotStatus.aspx.cs
MonkeyWrench.Web.UI/Code/Utils.cs
MonkeyWrench.Web.UI/Delete.aspx.cs
MonkeyWrench.Web.UI/EditHost.aspx.cs
MonkeyWrench.Web.UI/EditHosts.aspx.cs
MonkeyWrench.Web.UI/EditLane.aspx.cs
MonkeyWrench.Web.UI/EditLaneFile.aspx.cs
MonkeyWrench.Web.UI/EditLanes.aspx.cs
MonkeyWrench.Web.UI/GetRevisionLog.aspx.cs
MonkeyWrench.Web.UI/GetStatus.aspx.cs
MonkeyWrench.Web.UI/Global.asax.cs
MonkeyWrench.Web.UI/Identities.aspx.cs
MonkeyWrench.Web.UI/Login.aspx.cs
MonkeyWrench.Web.UI/Master.master.cs
MonkeyWrench.Web.UI/Notifications.aspx.cs
MonkeyWrench.Web.UI/Releases.aspx.cs
MonkeyWrench.Web.UI/ReportCommit.aspx.cs
MonkeyWrench.Web.UI/ReportGitHubCommit.aspx.cs
MonkeyWrench.Web.UI/SelectLanes.aspx.cs
MonkeyWrench.Web.UI/User.aspx.cs
MonkeyWrench.Web.UI/Users.aspx.cs
MonkeyWrench.Web.UI/ViewHostHistory.aspx.cs
MonkeyWrench.Web.UI/ViewHtmlReportEmbedded.aspx.cs
MonkeyWrench.Web.UI/ViewLane.aspx.cs
MonkeyWrench.Web.UI/ViewTable.aspx.cs
MonkeyWrench.Web.UI/ViewWorkTable.aspx.cs
MonkeyWrench.Web.UI/index.aspx.cs

The error handling in wrench primarily works by wrapping handler methods in `try { ... } catch(Exception ex} { ... }` blocks, and writing the error (and possibly the traceback) to the page.
This has multiple issues; the error handling code:
* is duplicated in every function,
* isn't standardized (some show just the exception message, some display both the message and traceback),
* displays the error to the user (tracebacks might contain sensitive information), and
* doesn't write the error to the log.
This patch removes most of the `try catch(Exception)` blocks in the web UI, and implements the error handling code in the `Global.Application_Error` method. The error handling code will log the error (with traceback) to wrench's logfile, then will display a generic "wrench has encountered an …

Better error handling in Web UI

---

MonkeyWrench.Web.UI/Global.asax.cs
MonkeyWrench.Web.UI/Master.master.cs
MonkeyWrench.Web.WebService/Authentication.cs

If `AllowAnonymousAccess` is set to false, then `Utils.LocalWebService.GetLeftTreeData` will throw an `HttpException` with the 403 error code. But `GetLeftTreeData` is called on the login page, so the login page will error out and effectively lock out everyone.
This patch changes the `Authentication` class to throw a new `UnauthorizedException` instead of a generic `HttpException`. It also modifies `Master.cs` to check for the exception when calling `GetLeftTreeData`, and to not display the sidebar data if caught.
This patch also checks for `UnauthorizedException` in the global `Application_Error` handler, and render a simple "Unauthorized" page if so. But since authorization is mostly checked in WebService functions, which still have their own per-function error handling, it's unlikely …

Added UnauthorizedException and check for it in Master and Global.

---

MonkeyWrench.Web.UI/Global.asax.cs

Apparently `Application_Error` also picks up the `HttpException` thrown when a client accesses a bad path. This modifies the error handler to display a simple 404 page when a page isn't found.

Display a 404 page when accessing an invalid route

---

MonkeyWrench.Web.WebService/Notifications/Notifications.cs

`queued_notifications` gets initialized after the thread has started, so the thread may attempt to poll a value from it before it gets initialized.
@rolfbjarne

Fixed a race condition when starting up notifiers.

---

MonkeyWrench.DataClasses/Database/DBRevisionWork.generated.cs
MonkeyWrench.DataClasses/Database/DBRevisionWorkView2.generated.cs
MonkeyWrench.DataClasses/SqlToCSharp.cs
MonkeyWrench.Database/Extensions/DBRevisionWork_Extensions.cs
MonkeyWrench.Web.UI/index.aspx.cs
MonkeyWrench.Web.WebService/WebNotification.cs
MonkeyWrench.Web.WebService/WebServices.asmx.cs
scripts/database.sql

This commit adds 3 columns and edits 1 column in the `RevisionWork` table:
* `CreatedTime`, which is the time that the work is created.
* `AssignedTime`, which is the time that the work is assigned to a bot.
* `StartedTime`, which is the time that the first step of the work is started.
* `EndTime`, which is the time that the work is completed (modified so that NULL is used instead of some date in 2000 as a 'not completed' value).
We're going to use these timings to track slow lanes and find bottlenecks (and make pretty charts).
I've previously kept this data in a separate `revisionwork_info_log` table, which is populated using database triggers when the `RevisionWork` table is changed, but this required the database to join the two (fairly large) tables together, resulting in poor …

Added timing information to revision works.

---

MonkeyWrench.Web.WebService/WebServices.asmx.cs

`GetMasterHosts` and `GetSlaveHosts` returned `null` instead of an empty list if it couldn't find any hosts, but the code that used those functions didn't check for that case. They now use `DBRecord.LoadMany` and return an empty list if nothing found.
This has already been deployed onto private wrench.
@rolfbjarne @duncanmak

Fixed null pointer exception on edit hosts page.

---

MonkeyWrench.Web.WebService/Scheduler/Scheduler.cs

These two messages are printed a lot (`lanes**hosts` times) and aren't very informative. This demotes them to debug level.
@rolfbjarne

Adjusted log levels in scheduler

---

MonkeyWrench.Database/DB.cs
MonkeyWrench.Web.UI/Global.asax.cs
MonkeyWrench.Web.UI/Json.aspx.cs

A coworker needed more info from the botinfo endpoint; this patch provides it.
It also fixes two bugs: one where the new time columns added to `RevisionWork` were not reset when resetting a `RevisionWork`, another with the error page using the target page's content-type.
@rolfbjarne @duncanmak

Expanded Json.aspx?type=botinfo

---

MonkeyWrench.Builder/Builder.cs

This allows the MSBuild-based scripts to also inject commands for Wrench.

Trim start of line since MSBuild indents the output

---

MonkeyWrench.Web.UI/Json.aspx.cs

The json output should also have the hosts current state.

Adding enabled field to botstatus JSON

---

MonkeyWrench.Database/DB.cs
MonkeyWrench.Web.UI/Json.aspx.cs
MonkeyWrench.Web.WebService/WebServices.asmx.cs

The lane info endpoint use to return a lanes object with key / values pairs where the key was the lane name. Lane tags have been added to the objects and now lanes is an array of lane objects.

Adding list of tags to laneinfo JSON endpoint and restructure as an array.

---

MonkeyWrench.Web.UI/Json.aspx.cs

Before the limit was overridden to just 1. Allow user to specify more than one.

Allow limit to be used with botstatus JSON endpoint.

---

MonkeyWrench.Web.WebService/Notifications/GitHubNotification.cs

It's tough to see what hosts the status belongs to without host names.

Add Hostname to github commit status message.

---

MonkeyWrench.Web.UI/Login.aspx.cs

We need to set the button visibility for the GitHub Oauth Login Button, same as we do for OAuth/OpenID. Right now it's appearing in general, even if you didn't set up the tokens in the config file.

Set GitHub Button Visibility on Login Init

---

MonkeyWrench.Web.UI/Json.aspx.cs

This should enable getting (nearly all of the) same data as is viewable on ViewLane in the JSON API, making it easier to consume when needing to do comparisons of jobs in, say, a chart form.

Add GetJobInfo to Json.aspx.cs

---

MonkeyWrench.Web.UI/GetLatest.aspx
MonkeyWrench.Web.UI/GetLatest.aspx.cs

Updated endpoint for getting the manifest from the latest revision with an uploaded build. There is a "prefer" parameter to specify if you want azure links or NAS links. If the azure link is not available, it defaults to NAS. Instead of redirecting, we just write the manifest directly to the page.
@duncanmak

Endpoint for getting the latest revision from any lane

---

MonkeyWrench.Web.UI/Json.aspx.cs

GetJobInfo in the API was actually getting the status info from ViewLane.aspx, so we should amend it to be called GetStatusInfo instead, since that's more accurate. I also added GetJobInfo to actually get the top level info on the job. The same as you would see on the top of ViewLane.

Add GetStatusInfo and amend GetJobInfo in Json.aspx

---

MonkeyWrench.Web.UI/GetManifest.aspx.cs
MonkeyWrench.Web.UI/GetMetadata.aspx.cs

Following comments from @duncanmak here https://github.com/mono/monkeywrench/pull/80#issuecomment-227778972
- Renamed `laneName` to `lane` for both endpoints.
- Returns a 404 page if it fails, instead of just rewriting the response.
- Removed `handleGetLatest` Action and turned it into a method.
- Changed names of methods and variables in GetMetadata to better reflect that it is, in fact, in GetMetadata.

Adjust GetManifest and GetMetadata Endpoints

---

MonkeyWrench.Web.UI/GetManifest.aspx.cs
MonkeyWrench.Web.UI/GetMetadata.aspx.cs

GetManifest and GetMetadata have logic to handle if the initial file requested does not exist. It _should_ fall back to NAS, or otherwise fail. However while it was expected as written that if it got a 404, it would return a failure response. It does not, it throws a `HttpWebException` of a 404. To get around this, I wrapped `makeHttpRequest` in a try catch. If it does get a WebException, it will return the failed response back. If there is some other exception, it will throw as normal.

Handle HTTP 404s for files in GetManifest and GetMetadata

---

MonkeyWrench.Database/Extensions/DBLogin_Extensions.cs
MonkeyWrench.Web.UI/Login.aspx.cs
MonkeyWrench.Web.WebService/WebServices.asmx.cs

The code for logging in with GitHub, while functional, was a bit hard to understand. So to make it easier and cleaner, I refactored it. The old login methods for OpenID/Google are back to how they were, while GitHub has its own method for logging in, with much simpler logic for handling it. It also has its own error message should the user not be able to log in.

Refactor GitHub login to make it simpler

---

MonkeyWrench.Web.UI/Login.aspx.cs
MonkeyWrench.Web.UI/ViewLane.aspx.cs

This uses the GitHub API to check if a lane is building a protected branch on GitHub.
If a branch is protected, or if the build is successful, we now hide the reset/abort/delete links.
This is to avoid accidentally reseting builds that have already gone into testing.

Hide protected branches

---

MonkeyWrench.Builder/Builder.cs

Thanks to @MSylvia for figuring this out.
@rolfbjarne Can we land this in?

Use Path.PathSeparator instead of hard-coding to ':'

---

MonkeyWrench.Builder/Builder.cs

Update Builder.cs to add timestamp on "Timed out" message. Helps when analyzing logs for timeout issues.

Update Builder.cs to add timestamp on "Timed out" message.

---

MonkeyWrench/Makefile

When generating the AssemblyInfo.cs file we end up with extra whitespace:
`[assembly: AssemblyVersion ("1.0.0.     787")]`
This compiled fine in previous versions of mono. But in 4.9.0 this is
enforced as invalid.
```
AssemblyInfo.cs(27,29): error CS7034: The specified version string does
not conform to the required format - major[.minor[.build[.revision]]]
```
This removes the extra whitespace and makes the version number valid.

Fix extra whitespace in AssemblyVersion

---

MonkeyWrench.Builder/Builder.cs

There's more to whitespace than just spaces, so don't specify just whitespace
to be trimmed from the start of a line. This should allow things like MSBuild/xbuild 
outputting tab-indented `@MonkeyWrench` commands to work correctly.

Builder: Trim all whitespace at start, not only spaces

---

MonkeyWrench.Database/Extensions/DBLogin_Extensions.cs
MonkeyWrench/Configuration.cs

Replace the string split code with structured XML.
The new format looks like this:
```
<GitHubOrganizationList>
<Team org="xamarin" team="Proprietary Access" role="Administrator" />
<Team org="xamarin" team="External" role="QualityAssurance" />
</GitHubOrganizationList >
```
Also print out the users org/teams if we fail to log in.

Better GitHub role mapping

---

MonkeyWrench.DataClasses/Database/DBLane.generated.cs
MonkeyWrench.DataClasses/Database/DBRevisionWork.generated.cs
MonkeyWrench.Web.UI/EditLane.aspx
MonkeyWrench.Web.UI/EditLane.aspx.cs
MonkeyWrench.Web.UI/EditLane.aspx.designer.cs
MonkeyWrench.Web.UI/ViewLane.aspx.cs
MonkeyWrench.Web.WebService/Scheduler/Scheduler.cs
MonkeyWrench/Configuration.cs
scripts/database.sql

This adds in a protected flag for all RevisionWork items in a Lane. Any build that finishes without error can not be reset (this includes builds with issues). There are some products that we ship even if there are test issues (like MonoDroid, e.g.), which is why they are included in this.
The RevisionWork will inherit the default protected value from the lane it belongs to. A quick SQL query can be made to switch the value if need be, though I could add in a UI element to do this if needed.
No builds will be retroactively set to protected; this is only a change for new builds going forward.

Customized message instead of reset button

---

MonkeyWrench.Web.UI/ViewLane.aspx.cs
MonkeyWrench.Web.WebService/WebServices.asmx.cs

Exposes a new API to get to a build in wrench solely from the commit and lane.
Might not bring you to the right build if there are multiple hosts, but that's not something we're too concerned about at present.

Search for revisionwork based on commit + lane

---

MonkeyWrench.DataClasses/Database/DBLane.generated.cs
MonkeyWrench.Database/DB.cs
MonkeyWrench.Web.UI/EditLane.aspx
MonkeyWrench.Web.UI/EditLane.aspx.cs
MonkeyWrench.Web.UI/EditLane.aspx.designer.cs
MonkeyWrench.Web.UI/ViewLane.aspx.cs
MonkeyWrench.Web.WebService/Scheduler/Scheduler.cs
MonkeyWrench.Web.WebService/Scheduler/SchedulerGIT.cs
MonkeyWrench.Web.WebService/WebServices.asmx.cs
scripts/database.sql

Primarily, this PR contains work to add in a new field for Lanes which specify how far back in the commit history to go when creating new builds after someone pushes. Unless changed, the default value set will cause Wrench to only pull the last commit.
Additionally, contains a few minor tweaks:
1) prevents the scheduler from querying lanes that have been disabled
2) causes cloned lanes to enable the same hosts as the master lane (less manual work)
3) fixes a bug where the protected lanes caused unfinished builds from being reset

Faster responsiveness

---

MonkeyWrench.Web.WebService/Scheduler/Scheduler.cs
scripts/database.sql

Explicitly mark all builds that aren't at the head of the tree when the scheduler runs as "Do not build" when populating the hostlane with new revisionworks.
I think this will (unfortunately) mess with the "delete build" button in that any build reset this way will be marked as ignored.

Top only builds

---

MonkeyWrench.Builder/Builder.cs

https://stackoverflow.com/questions/991537/how-do-i-determine-the-hresult-for-a-system-io-ioexception
It says Exception.HResult is public now, but I get this when I try to build 
error CS1540: Cannot access protected member `System.Exception.HResult' via a qualifier of type `System.Exception'. The qualifier must be of type `MonkeyWrench.Builder.Builder' or derived from it
I assumed that if the change happened in .net 4.5 it would work, but when I use xbuild or the new msbuild from VS for mac I get this error. Not sure what the approach should be, but using Marshal.GetHRForException() works.

Use method of getting hresult from older .net version
