mono/monkeywrench

MonkeyWrench.Database/DB.cs
MonkeyWrench/Configuration.cs

Added database name, user, and password configuration options.

---

MonkeyWrench.Web.WebService/Notifications/GitHubNotification.cs

Bypasses weirdness with GitHub notifications failing to connect with `ConnectFailure`.

Use curl to post to GitHub

---

MonkeyWrench.Web.WebService/WebServices.asmx.cs

This patch logs a message when an admin performs a couple of 'dangerous' actions, most notably modifying and deleting hosts and lanes.
These messages go to the log4net logger named `audit`, so they can be easily searched for (`grep 'audit -' logfile`) and, if needed later on, filtered to another log.
@rolfbjarne @duncanmak

Log some dangerous actions

---

MonkeyWrench.Web.WebService/Notifications/GitHubNotification.cs

Make curl print out the response code if a notification POST fails.

---

MonkeyWrench.Web.UI/Json.aspx.cs

Fixed Json.aspx returning old results for RevWorks without timing info

---

MonkeyWrench.Web.UI/ErrorPage.aspx.cs
MonkeyWrench.Web.UI/Global.asax.cs
MonkeyWrench.Web.UI/Login.aspx.cs

Redirect to accessed page after login.

---

MonkeyWrench.Web.WebService/WebServices.asmx.cs

Currently, ViewLane.aspx only uses the revision hash to query for revisions, but revisions are also keyed to the lanes they belong. This patch fixes the `GetViewLaneData2` function to query revisions using the lane id as well as the revision hash.
It also throws in a 404 page for nonexistant revision works, instead of failing with a null pointer exception.
@rolfbjarne @duncanmak

Fixed querying RevisionWorks by revision hash

---

MonkeyWrench.Web.WebService/Download.aspx.cs

Fixed redirect for downloading files such as logs

---

MonkeyWrench.Web.WebService/WebServices.asmx.cs

Don't check for a null host in GetViewLaneData2; it breaks pipeline

---

MonkeyWrench.Web.UI/Json.aspx.cs

A simple addition that would allow us to get the last job the bot was doing and the last time it checked in in a single api call.

Adding a bot status JSON endpoint that lists last job and time seen.

---

MonkeyWrench.Web.UI/Json.aspx.cs

This is somewhat tested. It compiles fine but I don't have enough test data in my local dev environment to see if it returns the correct results.

Adding json endpoint to show build status for lanes with tag

---

MonkeyWrench.Web.UI/Json.aspx.cs

Renamed the endpoint to match the scheme of the others.
Data added to returned results:
* host_id
* host

Renamed JSON endpoint to taginfo. Added host and host_id

---

MonkeyWrench.Web.UI/index.aspx.cs

This fixes the jagged table edges in the tags lane view.

Fix jagged table edges

---

MonkeyWrench.Web.UI/Json.aspx.cs

Adding 2 new keys to the returned data.

Adding description and architecture to botstatus JSON endpoint

---

MonkeyWrench.Web.UI/Json.aspx.cs

Needed to add these for @drasticactions

Adding lane_id and revision_id to JSON endpoint

---

MonkeyWrench.Web.UI/Json.aspx.cs

To get some data on how we are doing with build and step times I've added a JSON endpoint to gather that information.

Adding json endopint for worktable info

---

MonkeyWrench.Builder/Builder.cs
MonkeyWrench/ProcessHelper.cs
MonkeyWrench/ProcessHelperLinux.cs
MonkeyWrench/ProcessHelperMac.cs
MonkeyWrench/ProcessHelperWindows.cs

Better diagnostics when timing out and killing our processes

Process name

---

MonkeyWrench.Web.UI/Json.aspx.cs

The `laneinfo` query is missing hosts.

[JSON] Add hosts to laneinfo

---

MonkeyWrench/Configuration.cs

Tested using the docker container
https://wrench.internalx.com/Wrench/WebServices/Download.aspx?workfile_id=17642518

Use the system defined path separator

---

MonkeyWrench.Database/DB.cs
MonkeyWrench.Web.WebService/WebServices.asmx.cs

New lane creation defaults to 0 (lowest) priority

Ensure all new lanes have default priority

---

MonkeyWrench.Builder/Builder.cs

We are trying to report better messages in our slack API, and we need a way to collect concise messages from wrench without the stacktrace. This is the best way I could think of.
The more important part of this PR is that it tests explicitly for disk full exceptions, since that is the most important in terms of building and we want to be able to report it specifically so we can act accordingly.

Use *** for log message delimiter, and add explicit messaging for full disk

---

MonkeyWrench.Web.UI/EditHost.aspx
MonkeyWrench.Web.UI/EditHost.aspx.cs

Provides more information about slave host that may be useful in decision to remove.

Add description to slave hosts in edit host page for more info
